### ISSUE TITLE
Erronous Syntax Error reported into XData blocks for "&|" character

### ISSUE THREAD

**Issue by GendronAC** [intersystems/language-server#148]
# How to reproduce # 
 + Create an XData in a file with the following content : 
```
XData SomeMessage
{
<CDATA>
Some &| content
</CDATA>
}
```

# The problem #
Syntax error reported by VSCode
![image](https://user-images.githubusercontent.com/45271725/112178781-6e9a5a80-8bd0-11eb-83bf-756c81f16839.png)

# How I worked-around #
```
XData SomeMessageEscaped
{
<CDATA>
Some &amp;| content
</CDATA>
}
```

This causes issue with some of our HL7 messages stored in XData for some unit tests : 
![image](https://user-images.githubusercontent.com/45271725/112178986-a1445300-8bd0-11eb-98b7-6bb6aca04721.png)

**Comment by isc-bsaviano** [comment]
@GendronAC Do you get this same error in Studio?

**Comment by GendronAC** [comment]
Nope, the files itself compiles without error and runs fine both from Visual Studio and Studio. The issue is really related to that "false positive" error.

**Comment by isc-bsaviano** [comment]
@GendronAC I just checked Studio and the syntax error shows up there as well. This is expected because the language server uses Studio's parsers to do the coloring and error diagnostics. I will assign this to the developer who maintains the parsers and he will take a look.

**Comment by GendronAC** [comment]
You are right, I'm sorry, the error is indeed underlined in Studio

**Comment by isc-AndrewCheshire** [comment]
@GendronAC The `CDATA` construct is introduced using a special syntax rather than as a `<CDATA>` tag.

A `CDATA` section begins with `<![CDATA[` and ends with `]]>`.  Absolutely *anything* can be put between those "brackets" - except the closing `]]>` sequence itself.

A `CDATA` section is legal in XML *content*, i.e. between XML tags such as `<abc>` and `</abc>`.  Other content - either plain text or other `CDATA` sections - can appear before or after a `CDATA` section.

For example:

``` xml
<abc>
some text
<![CDATA[
&|
]]>
some text
</abc>
```

I've put the `&|` on a line to itself so that the example is easier to read but this is also valid:

``` xml
<abc>
some text
<![CDATA[&|]]>
some text
</abc>
```

**Comment by isc-bsaviano** [comment]
Closing this because it's not an issue with our parsers
