### ISSUE TITLE
#dim not proposing all members

### ISSUE THREAD

**Issue by isc-solon** [intersystems/language-server#242]
When I enter something like this:
```
#dim ex as %Exception.SystemException
set ex = ##class(%Exception.SystemException).%New()
write ex.
```
The basic properties of the class aren't proposed, such as Name and Code (inherited from %Exception.CPPException). What is proposed are the methods NameGet() and CodeGet(). These are overridden methods in SystemException.

So it appears that #dim is not proposing members from the superclasses, only the current class.

**Comment by isc-bsaviano** [comment]
@isc-solon This appears to be a weird edge case that specially effects `%Exception.SystemException`. I looked queried the `%Dictionary.CompiledProperty` table and can observe that property inheritance works, even for `%Exception` classes. For example, if you change `%Exception.SystemException` to `%Exception.PythonException`, you will seethe inherited properties (although they will down in the list because members from the current class are always bubbled to the top).

**Comment by isc-bsaviano** [comment]
@isc-solon This is caused by `%Exception.SystemException` being a system class. For system classes the inheritance resolution is done in the kernel and is not in `^oddCOM`, which is why the intellisense isn't showing up. There's nothing that I can do to get that information.
