### ISSUE TITLE
Linting for embedded Javascript

### ISSUE THREAD

**Issue by LogMull** [intersystems/language-server#262]
Is there an existing way to run any kind of linting against embedded javascript in objectscript classes? If not, is that something that is planned / reasonable to expect in the future? My team makes heavy use of the embedded javascript and not having any kind of linting on it has been a pain point.

**Comment by isc-bsaviano** [comment]
@LogMull This isn't something that is likely to be implemented anytime soon. We added support for some intellisense in [version 2.1.0](https://github.com/intersystems/language-server/blob/master/CHANGELOG.md#210---2022-08-04) but linting would be much more difficult because most embedded JS is "infected" with embedded ObjectScript and any existing JS linter wouldn't handle that well. For things like hover and code completion that's not a big deal since you just won't get intellisense in some places, but if you get a huge number of false problems reported that is a very bad user experience.

**Comment by LogMull** [comment]
I assumed it was not on the radar due to reasons like that.  Thanks for the clarification and quick response!
