### ISSUE TITLE
In instance methods, should get auto-completion for i% properties

### ISSUE THREAD

**Issue by isc-kiyer** [intersystems/language-server#292]
In instance methods, to access the true value of a property (bypass the getters and setters), the i% syntax is used. There is autocompletion for .. syntax but not for i% syntax.
This is a request to add autocompletion of class properties when using the i% syntax.

**Comment by isc-bsaviano** [comment]
@isc-kiyer I can add completion, hover and definition support for this pretty easily, but there is one issue. Having the completion trigger automatically requires adding "%" as a trigger character. I don't want to do that because "%" appears very often and this would cause existing completions to "disappear" when a "%" is typed (for example, in a class name or method name). What I'll do is add the support anyways, but you'll have to manually trigger it using Ctrl-Space after you type "i%".

**Comment by isc-bsaviano** [comment]
Only single characters are allowed AFAICT.
