### ISSUE TITLE
When using client side source control, go to definition should use the local file and not open the server version

### ISSUE THREAD

**Issue by bourette** [intersystems/language-server#45]
When using client side source control if a method or property is in the open class go to definition should not open the server side version of the class, but instead it should go to the method or property within the open class.

**Comment by isc-bsaviano** [comment]
@bourette I spoke with @isc-jamien and we determined that this isn't feasible. Since the server can't guarantee that local files are named properly (i.e. /User/test.cls really corresponds to User.test), that classes aren't duplicated or that the local copy is in sync with the server, we agreed that the server should be the "source of truth".

**Comment by daimor** [comment]
I disagree with this, current behavior is a regression and have to be fixed, to be the same as previously with ObjectScript extension

Go to server's file, while working locally, and having it locally, make no sense at all.
It makes it much more difficult to work.

Developer expects Go To defintion, will open a local file which will be possible to edit, but not read-only file.

**Comment by isc-jamien** [comment]
@daimor we will discuss at the PMC

**Comment by gjsjohnmurray** [comment]
The approach used by the ObjectScript Explorer (OE) view may be worth taking. Here's a screenshot of client-side development in a namespace for which I have only exported a subset of the classes, namely the Codis package:

![image](https://user-images.githubusercontent.com/6726799/97450738-f5515100-192a-11eb-9871-31e72b1a4803.png)

Notice how classes in Codis get an icon, but classes in WebTerminal don't.

If I open a Codis one from OE I get an editable local file.

If I open a WebTerminal one I get a readonly document, pulled from the server.

I think Go to Definition should target the local copy if it exists, and fall back to loading from the server if not. You'll probably need another API endpoint in vscode-objectscript in order to achieve this.

_Originally posted by @gjsjohnmurray in https://github.com/intersystems/language-server/issues/50#issuecomment-717991205_

**Comment by isc-bsaviano** [comment]
I think that if the PMC decides that we should implement this, exposing the DocumentContentProvider:getUri() function as an exported API (maybe with some modification because the LS doesn't have knowledge of workspaces currently) will be necessary.
