### ISSUE TITLE
Go to definition for method of current class in client-side editing mode shouldn't open server version 

### ISSUE THREAD

**Issue by isc-bsaviano** [intersystems/language-server#50]
Suggested by @bourette

**Comment by gjsjohnmurray** [comment]
Arose from #45

**Comment by gjsjohnmurray** [comment]
The approach used by the ObjectScript Explorer (OE) view may be worth taking. Here's a screenshot of client-side development in a namespace for which I have only exported a subset of the classes, namely the Codis package:

![image](https://user-images.githubusercontent.com/6726799/97450738-f5515100-192a-11eb-9871-31e72b1a4803.png)

Notice how classes in Codis get an icon, but classes in WebTerminal don't.

If I open a Codis one from OE I get an editable local file.

If I open a WebTerminal one I get a readonly document, pulled from the server.

I think Go to Definition should target the local copy if it exists, and fall back to loading from the server if not. You'll probably need another API endpoint in vscode-objectscript in order to achieve this.

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray This issue is for the specific case where the class member that we're looking up is in the local file that you have open already so I don't need to generate a new URI. We should keep the discussion for the general case on #45

**Comment by gjsjohnmurray** [comment]
@isc-bsaviano sure, in which case please reopen #45.
