### ISSUE TITLE
Provide a CONTRIBUTING.md

### ISSUE THREAD

**Issue by mvhenderson** [intersystems/language-server#58]
Looking for a `CONTRIBUTING.md` similar to the `vscode-objectscript` project to help those of us new to working with the VSCode stack. Ideally would cover how to run all the objectscript simultaneously in dev/debug mode.

**Comment by daimor** [comment]
This extension is not ready for contribution, yet. Due to missing some of the binaries in public. When this issue will be solved, it will be possible to provide a way how to run it. But anyway, VSCode supports to run only one extension in the debug mode. But this extension uses a language server, which will be in debug mode as well if any extension is under debugging.

**Comment by mvhenderson** [comment]
Fair enough. There are a few bugs I was hoping to gather more detail on before submitting issue. Both deal with theme/syntax-highlighting are are difficult to reproduce consistently but only happen when semantic highlighting is enabled. I'll see how far debugging the `vscode-objectscript` extension gets me.
